name: CI
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Tree
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Create Z3 Build Directory
      run: mkdir ${{runner.workspace}}/vampire/z3/build
    - name: Cache Z3 Build
      uses: actions/cache@v2
      with:
        path: ${{runner.workspace}}/vampire/z3/build
        key: ${{runner.os}}-z3-${{hashFiles('.git/modules/z3/HEAD')}}
    - name: Configure Z3 Build
      working-directory: ${{runner.workspace}}/vampire/z3/build
      run: cmake .. -DCMAKE_BUILD_TYPE=Debug
      env:
        CXX: clang++
    - name: Z3 Build
      working-directory: ${{runner.workspace}}/vampire/z3/build
      run: make -j8
    - name: Create Build Directory
      run: mkdir ${{runner.workspace}}/vampire/build
    - name: Configure Build
      working-directory: ${{runner.workspace}}/vampire/build
      run: cmake .. -DCMAKE_BUILD_TYPE=Debug
      env:
        CXX: clang++
    - name: Build
      working-directory: ${{runner.workspace}}/vampire/build
      run: make -j8
